server:
  port: 8010
spring:
  application:
    name: manager-server  #服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #nacos的服务注册中心地址
feign:
  sentinel:
    enabled: true